server:
  port: 8079
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    client-server:
      path: /client-server/**
      serviceId: client-server
    eureka:
      path: /eureka/**
      serviceId: eureka
spring:
  application:
    name: zuul-service